
    if (Math.random() < 0.05) {
        
        document.body.innerHTML = "<h1>say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley say hello to Rick Astley</h1>";

        
        setTimeout(function() {
            
            window.location.href = "https://www.youtube.com/watch?v=uHgt8giw1LY";
        }, 1000); 
    }

